version: "3"
services:
    zabbixdb:
        image: mysql
        restart: always
        networks:
            zabbixnetwork:
                ipv4_address: "192.168.123.13"
        environment:
            MYSQL_ROOT_PASSWORD: "Abc123456"
        volumes:
            - ./mysql:/var/lib/mysql
    zabbixapp:
        image: zabbix/zabbix-server-mysql
        ports:
            - "10051:10051"
        restart: always
        networks:
            zabbixnetwork:
                ipv4_address: "192.168.123.12"
        environment:
            DB_SERVER_HOST: "zabbixdb"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "Abc123456"
        depends_on:
            - zabbixdb
    zabbixweb:
        image: zabbix/zabbix-web-nginx-mysql
        ports:
            - "8080:8080"
        restart: always
        networks:
            zabbixnetwork:
                ipv4_address: "192.168.123.11"
        environment:
            DB_SERVER_HOST: "zabbixdb"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "Abc123456"
            ZBX_SERVER_HOST: "192.168.123.12"
            PHP_TZ: "Asia/Kuala_Lumpur"
        depends_on:
            - zabbixdb
networks:
    zabbixnetwork:
        ipam:
            driver: default
            config:
                - subnet: "192.168.123.0/24"
